-- ─── Seed Ophthalmology Medications for All Tenants ──────────────────────────
-- Migration 37: Ensures every tenant has the standard 39 ophth medications.
-- Safe to re-run: ON CONFLICT (tenant_id, generic_name) DO NOTHING.
-- ─────────────────────────────────────────────────────────────────────────────

DO $$
DECLARE
    v_tenant RECORD;
BEGIN
    FOR v_tenant IN SELECT id FROM tenant WHERE deleted_at IS NULL LOOP
        INSERT INTO ophth_medication (
            id, tenant_id, generic_name, brand_names, drug_class,
            indications, contraindications, warnings, pregnancy_category,
            route, common_side_effects, serious_side_effects, status, created_at
        )
        SELECT
            gen_random_uuid(),
            v_tenant.id,
            m.generic_name, m.brand_names, m.drug_class,
            m.indications, m.contraindications, m.warnings, m.pregnancy_category,
            m.route, m.common_side_effects, m.serious_side_effects,
            'active', NOW()
        FROM (VALUES
            -- GLAUCOMA
            ('Timolol 0.5%',         ARRAY['Timoptic','Betimol'],              'Beta-blocker',                    'Primary open-angle glaucoma, Ocular hypertension',         'Asthma, COPD, Heart block, Severe cardiac failure',         'Monitor heart rate and blood pressure. May mask signs of hypoglycemia.', 'C', 'Topical', ARRAY['Stinging','Blurred vision','Eye irritation'],                       ARRAY['Bradycardia','Bronchospasm','Heart failure','Syncope']),
            ('Latanoprost 0.005%',   ARRAY['Xalatan'],                         'Prostaglandin analog',            'Primary open-angle glaucoma, Ocular hypertension',         'Pregnancy, Active intraocular inflammation',                 'May cause iris darkening, eyelash changes. Use in evening only.',        'C', 'Topical', ARRAY['Eye redness','Iris darkening','Eyelash growth'],                      ARRAY['Macular edema','Iritis','Uveitis']),
            ('Brimonidine 0.2%',     ARRAY['Alphagan'],                        'Alpha-2 agonist',                 'Ocular hypertension, Open-angle glaucoma',                  'MAO inhibitor therapy, Age <2 years',                       'Avoid in neonates and infants. May cause CNS depression in children.',   'B', 'Topical', ARRAY['Dry mouth','Eye allergy','Drowsiness'],                               ARRAY['Hypotension','Bradycardia','CNS depression']),
            ('Dorzolamide 2%',       ARRAY['Trusopt'],                         'Carbonic anhydrase inhibitor',    'Open-angle glaucoma, Ocular hypertension',                  'Severe renal impairment, Sulfa allergy',                     'Contains sulfonamide. Monitor for signs of Stevens-Johnson syndrome.',   'C', 'Topical', ARRAY['Bitter taste','Burning','Blurred vision'],                            ARRAY['Stevens-Johnson syndrome','Toxic epidermal necrolysis']),
            ('Acetazolamide 250mg',  ARRAY['Diamox'],                          'Carbonic anhydrase inhibitor',    'Acute angle-closure glaucoma',                              'Sulfa allergy, Severe renal/hepatic disease, Hypokalemia',  'Monitor electrolytes, especially potassium.',                            'C', 'Oral',    ARRAY['Tingling in extremities','Frequent urination','Taste changes'],      ARRAY['Stevens-Johnson syndrome','Severe metabolic acidosis','Aplastic anemia']),
            -- ANTI-INFLAMMATORY
            ('Prednisolone Acetate 1%', ARRAY['Pred Forte'],                   'Corticosteroid',                  'Uveitis, Post-operative inflammation, Allergic conjunctivitis','Viral eye infections, Fungal eye diseases',               'Prolonged use may cause glaucoma, cataract, delayed wound healing.',     'C', 'Topical', ARRAY['Burning','Stinging','Blurred vision'],                               ARRAY['Increased IOP','Cataract formation','Secondary infections']),
            ('Dexamethasone 0.1%',   ARRAY['Maxidex'],                         'Corticosteroid',                  'Allergic conjunctivitis, Uveitis, Post-operative inflammation','Viral infections, Fungal eye disease',                   'Monitor IOP with prolonged use. Taper gradually.',                      'C', 'Topical', ARRAY['Burning','Stinging'],                                                 ARRAY['Glaucoma','Cataract','Secondary infection']),
            ('Ketorolac 0.5%',       ARRAY['Acular'],                          'NSAID',                           'Post-operative inflammation, Seasonal allergic conjunctivitis','Aspirin sensitivity, Bleeding disorders',                 'May slow wound healing after surgery.',                                  'C', 'Topical', ARRAY['Stinging','Burning'],                                                 ARRAY['Corneal erosion','Corneal perforation','Bleeding']),
            ('Nepafenac 0.1%',       ARRAY['Nevanac'],                         'NSAID',                           'Post-operative inflammation (cataract surgery)',             'Aspirin allergy',                                           'Use with caution in complicated surgeries.',                             'C', 'Topical', ARRAY['Eye discomfort','Photophobia'],                                       ARRAY['Corneal erosion','Corneal thinning']),
            -- ANTIBIOTICS
            ('Moxifloxacin 0.5%',    ARRAY['Vigamox'],                         'Fluoroquinolone antibiotic',      'Bacterial conjunctivitis, Corneal ulcer prophylaxis',        'Fluoroquinolone hypersensitivity',                          'Do not use with contact lenses.',                                        'C', 'Topical', ARRAY['Eye irritation','Tearing'],                                          ARRAY['Corneal perforation (with ulcer)','Hypersensitivity reactions']),
            ('Ciprofloxacin 0.3%',   ARRAY['Ciloxan'],                         'Fluoroquinolone antibiotic',      'Bacterial keratitis, Corneal ulcer',                         'Fluoroquinolone allergy',                                   'May produce white crystalline precipitate.',                             'C', 'Topical', ARRAY['White crystals','Burning'],                                          ARRAY['Corneal perforation','Tendon rupture (systemic)']),
            ('Tobramycin 0.3%',      ARRAY['Tobrex'],                          'Aminoglycoside antibiotic',       'External ocular infections',                                'Aminoglycoside hypersensitivity',                           'Prolonged use may result in overgrowth of non-susceptible organisms.',   'B', 'Topical', ARRAY['Eye irritation','Redness'],                                          ARRAY['Ototoxicity (systemic use)','Nephrotoxicity (systemic)']),
            ('Azithromycin 1%',      ARRAY['AzaSite'],                         'Macrolide antibiotic',            'Bacterial conjunctivitis',                                  'Macrolide hypersensitivity',                                'Well tolerated. Unique dosing schedule.',                                'B', 'Topical', ARRAY['Eye irritation'],                                                     ARRAY['Rare hypersensitivity']),
            -- ANTI-VIRAL
            ('Acyclovir 3%',         ARRAY['Zovirax'],                         'Antiviral',                       'Herpes simplex keratitis',                                  'Hypersensitivity to acyclovir',                             'Complete treatment course. Monitor for recurrence.',                     'B', 'Topical', ARRAY['Mild burning','Stinging'],                                            ARRAY['Hypersensitivity reactions']),
            ('Ganciclovir 0.15%',    ARRAY['Zirgan'],                          'Antiviral',                       'Acute herpetic keratitis',                                  'Hypersensitivity',                                          'More effective than acyclovir for herpes keratitis.',                    'C', 'Topical', ARRAY['Blurred vision','Eye irritation'],                                   ARRAY['Bone marrow suppression (systemic)']),
            -- ANTI-FUNGAL
            ('Natamycin 5%',         ARRAY['Natacyn'],                         'Antifungal',                      'Fungal keratitis, Fungal conjunctivitis',                    'Hypersensitivity',                                          'Only antifungal eye drop available.',                                    'C', 'Topical', ARRAY['Eye irritation','Tearing'],                                          ARRAY['Rare hypersensitivity']),
            -- MYDRIATICS / CYCLOPLEGICS
            ('Tropicamide 1%',       ARRAY['Mydriacyl'],                       'Mydriatic/Cycloplegic',           'Pupil dilation for examination, Cycloplegic refraction',    'Angle-closure glaucoma, Hypersensitivity',                  'Short-acting. Warn patients about temporary vision blur.',               'C', 'Topical', ARRAY['Stinging','Photophobia','Blurred vision'],                           ARRAY['Angle-closure glaucoma attack','Tachycardia']),
            ('Cyclopentolate 1%',    ARRAY['Cyclogyl'],                        'Cycloplegic/Mydriatic',           'Cycloplegic refraction, Uveitis',                           'Angle-closure glaucoma',                                   'More potent cycloplegia than tropicamide.',                              'C', 'Topical', ARRAY['Burning','Photophobia','Blurred vision'],                            ARRAY['CNS disturbances in children','Angle-closure attack']),
            ('Atropine 1%',          ARRAY['Isopto Atropine'],                 'Cycloplegic/Mydriatic',           'Cycloplegic refraction in children, Uveitis, Amblyopia',    'Angle-closure glaucoma',                                   'Long-acting (7-14 days). May cause systemic anticholinergic effects.',  'C', 'Topical', ARRAY['Photophobia','Blurred vision','Dry mouth'],                           ARRAY['Fever','Tachycardia','CNS effects','Urinary retention']),
            ('Phenylephrine 2.5%',   ARRAY['Mydfrin'],                         'Mydriatic',                       'Pupil dilation for examination',                            'Angle-closure glaucoma, Cardiovascular disease',           'Avoid 10% concentration in elderly. Monitor blood pressure.',            'C', 'Topical', ARRAY['Stinging','Rebound miosis'],                                        ARRAY['Hypertensive crisis','Myocardial infarction','Stroke']),
            -- DRY EYE
            ('Cyclosporine 0.05%',   ARRAY['Restasis'],                        'Immunomodulator',                 'Chronic dry eye disease',                                   'Active eye infection',                                      'Takes 3-6 months for full effect.',                                      'C', 'Topical', ARRAY['Burning','Eye redness'],                                             ARRAY['Rare hypersensitivity']),
            ('Lifitegrast 5%',       ARRAY['Xiidra'],                          'Integrin antagonist',             'Dry eye disease',                                           'Hypersensitivity',                                          'Newer agent. Alternative to cyclosporine.',                              'C', 'Topical', ARRAY['Dysgeusia (bad taste)','Eye irritation'],                            ARRAY['Hypersensitivity reactions']),
            ('Artificial Tears',     ARRAY['Systane','Refresh','GenTeal'],     'Lubricant',                       'Dry eye, Contact lens comfort',                             'Hypersensitivity to preservatives',                         'Preservative-free formulations preferred for frequent use.',             'N/A','Topical', ARRAY['Temporary blurred vision'],                                        ARRAY['None']),
            -- ANTI-VEGF INTRAVITREAL
            ('Ranibizumab',          ARRAY['Lucentis'],                        'Anti-VEGF',                       'Wet AMD, Diabetic macular edema, RVO',                      'Ocular/periocular infection, Intraocular inflammation',     'Risk of endophthalmitis, retinal detachment, increased IOP.',            'C', 'Intravitreal', ARRAY['Eye pain','Floaters','Conjunctival hemorrhage'],                ARRAY['Endophthalmitis','Retinal detachment','Stroke','MI']),
            ('Aflibercept',          ARRAY['Eylea'],                           'Anti-VEGF',                       'Wet AMD, Diabetic macular edema, DME, RVO',                 'Ocular/periocular infection',                               'Less frequent dosing than ranibizumab.',                                  'C', 'Intravitreal', ARRAY['Conjunctival hemorrhage','Eye pain'],                           ARRAY['Endophthalmitis','Retinal detachment','Thromboembolic events']),
            ('Bevacizumab',          ARRAY['Avastin'],                         'Anti-VEGF',                       'Off-label: Wet AMD, DME, RVO',                              'Active infection',                                          'Off-label use but widely used. Much less expensive than alternatives.',  'C', 'Intravitreal', ARRAY['Eye pain','Floaters'],                                          ARRAY['Endophthalmitis','Retinal detachment','Stroke']),
            -- CORTICOSTEROID INTRAVITREAL
            ('Triamcinolone',        ARRAY['Triesence','Trivaris'],            'Corticosteroid',                  'Macular edema, Uveitis',                                    'Ocular infections',                                         'Risk of cataract and glaucoma with repeated injections.',                'C', 'Intravitreal', ARRAY['Increased IOP','Eye pain'],                                    ARRAY['Cataract','Glaucoma','Endophthalmitis']),
            ('Dexamethasone implant',ARRAY['Ozurdex'],                         'Corticosteroid implant',          'Macular edema (RVO, DME), Non-infectious uveitis',          'Glaucoma, Ocular infections',                               'Sustained-release implant lasting ~6 months. Monitor IOP closely.',     'C', 'Intravitreal', ARRAY['Increased IOP','Cataract progression'],                        ARRAY['Severe glaucoma','Endophthalmitis','Retinal detachment']),
            -- MIOTICS
            ('Pilocarpine 2%',       ARRAY['Isopto Carpine'],                  'Miotic/Cholinergic',              'Angle-closure glaucoma, Post-mydriasis',                    'Acute iritis, Pupillary block glaucoma',                   'Causes miosis and blurred vision. Warn patients about night driving.',   'C', 'Topical', ARRAY['Brow ache','Blurred vision','Myopia'],                               ARRAY['Retinal detachment','Lens-iris diaphragm retropulsion']),
            -- ANTIHISTAMINE / MAST CELL STABILIZERS
            ('Olopatadine 0.2%',     ARRAY['Pataday','Patanol'],               'Antihistamine/Mast cell stabilizer','Allergic conjunctivitis',                               'Hypersensitivity',                                          'Very effective for allergic eye symptoms. Once daily dosing.',           'C', 'Topical', ARRAY['Mild burning'],                                                       ARRAY['Rare hypersensitivity']),
            ('Ketotifen 0.025%',     ARRAY['Zaditor'],                         'Antihistamine/Mast cell stabilizer','Allergic conjunctivitis',                               'Hypersensitivity',                                          'Available over-the-counter. Good for seasonal allergies.',               'C', 'Topical', ARRAY['Mild irritation'],                                                    ARRAY['Rare hypersensitivity']),
            ('Cromolyn 4%',          ARRAY['Crolom'],                          'Mast cell stabilizer',            'Allergic conjunctivitis',                                   'Hypersensitivity',                                          'Prevents histamine release. Less effective than dual-action drugs.',     'B', 'Topical', ARRAY['Stinging'],                                                           ARRAY['Rare']),
            -- SYSTEMIC (common interactions)
            ('Aspirin 75-325mg',     ARRAY['Ecosprin','Disprin'],              'Antiplatelet',                    'Cardiovascular disease prevention',                         'Bleeding disorders, Active GI bleeding',                    'Increases bleeding risk perioperatively. Hold 7-10 days before surgery.','D', 'Oral',    ARRAY['GI upset','Bruising'],                                                ARRAY['GI bleeding','Hemorrhagic stroke']),
            ('Warfarin',             ARRAY['Coumadin'],                        'Anticoagulant',                   'Atrial fibrillation, DVT/PE prevention',                    'Active bleeding, Pregnancy',                                'Requires INR monitoring. High bleeding risk with ocular procedures.',    'X', 'Oral',    ARRAY['Bruising','Bleeding'],                                                ARRAY['Intracranial hemorrhage','Retinal hemorrhage','Hyphema']),
            ('Tamsulosin',           ARRAY['Flomax'],                          'Alpha-blocker',                   'Benign prostatic hyperplasia',                              'Severe hepatic impairment',                                 'Causes Intraoperative Floppy Iris Syndrome (IFIS).',                     'B', 'Oral',    ARRAY['Dizziness','Rhinitis'],                                               ARRAY['IFIS','Hypotension','Syncope']),
            ('Hydroxychloroquine',   ARRAY['Plaquenil'],                       'Antimalarial/DMARD',              'Rheumatoid arthritis, Lupus, Malaria',                      'Retinal/visual field changes',                              'Requires baseline and annual retinal screening.',                        'C', 'Oral',    ARRAY['Nausea','Headache'],                                                  ARRAY['Retinal toxicity (bull''s eye maculopathy)','Cardiomyopathy']),
            ('Ethambutol',           ARRAY['Myambutol'],                       'Antimycobacterial',               'Tuberculosis',                                              'Optic neuritis',                                           'Monitor visual acuity and color vision monthly.',                        'B', 'Oral',    ARRAY['Nausea','Headache'],                                                  ARRAY['Optic neuritis','Vision loss','Color blindness']),
            ('Sildenafil',           ARRAY['Viagra'],                          'PDE-5 inhibitor',                 'Erectile dysfunction',                                      'Nitrate use, Recent MI/stroke',                             'May cause transient blue vision. Avoid in NAION.',                       'B', 'Oral',    ARRAY['Headache','Flushing','Blue tinge to vision'],                        ARRAY['NAION','Priapism','Sudden hearing loss']),
            ('Amiodarone',           ARRAY['Cordarone'],                       'Antiarrhythmic',                  'Atrial fibrillation, Ventricular arrhythmias',              'Severe sinus node dysfunction',                             'Causes corneal deposits (vortex keratopathy) in nearly all patients.',   'D', 'Oral',    ARRAY['Corneal deposits','Photosensitivity'],                               ARRAY['Optic neuropathy','Vision loss','Thyroid dysfunction']),
            ('Isotretinoin',         ARRAY['Accutane','Roaccutane'],           'Retinoid',                        'Severe acne',                                               'Pregnancy, Vitamin A supplementation',                      'Causes severe dry eyes and blepharitis.',                                'X', 'Oral',    ARRAY['Dry eyes','Blepharitis','Photophobia'],                              ARRAY['Intracranial hypertension','Corneal opacities','Vision changes'])
        ) AS m(generic_name, brand_names, drug_class, indications, contraindications, warnings, pregnancy_category, route, common_side_effects, serious_side_effects)
        WHERE NOT EXISTS (
            SELECT 1 FROM ophth_medication
            WHERE tenant_id = v_tenant.id AND generic_name = m.generic_name AND deleted_at IS NULL
        );
    END LOOP;

    RAISE NOTICE '✅ Ophthalmology medications seeded for all tenants';
END $$;
