'use client';

import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { Plus, RefreshCw, Search, Package, X, CheckCircle, XCircle, Send, GitBranch, ShoppingCart } from 'lucide-react';
import { toast } from 'react-hot-toast';
import Link from 'next/link';
import {
  inventoryRequisitionApi,
  inventoryItemApi,
  ItemDto,
  VendorDto,
  EvaluatePolicyPathResult,
  type ConvertToPORequest,
} from '@/lib/api/inventory-service.api';
import { branchesApi } from '@/lib/api';
import { useStores, useInventoryItems } from '@/hooks/useInventoryReferenceData';

const STATUS_TABS = [
  { key: 'All',            label: 'All',             dot: 'bg-slate-400',    activeClass: 'bg-slate-600 border-slate-600 text-white' },
  { key: 'Draft',          label: 'Draft',           dot: 'bg-amber-400',    activeClass: 'bg-amber-500 border-amber-500 text-white' },
  { key: 'Submitted',      label: 'Submitted',       dot: 'bg-blue-400',     activeClass: 'bg-blue-500 border-blue-500 text-white' },
  { key: 'Approved',       label: 'Approved',        dot: 'bg-green-400',    activeClass: 'bg-green-600 border-green-600 text-white' },
  { key: 'Rejected',       label: 'Rejected',        dot: 'bg-red-400',      activeClass: 'bg-red-500 border-red-500 text-white' },
  { key: 'AutoGenerated',  label: 'Auto-Generated',  dot: 'bg-purple-400',   activeClass: 'bg-purple-600 border-purple-600 text-white' },
  { key: 'ConvertedToRFQ', label: 'To RFQ',          dot: 'bg-cyan-400',     activeClass: 'bg-cyan-600 border-cyan-600 text-white' },
  { key: 'ConvertedToPO',  label: 'To PO',           dot: 'bg-emerald-400',  activeClass: 'bg-emerald-600 border-emerald-600 text-white' },
];

const STATUS_BORDER: Record<string, string> = {
  Draft: 'border-l-amber-400', Submitted: 'border-l-blue-400', Approved: 'border-l-green-500',
  Rejected: 'border-l-red-400', AutoGenerated: 'border-l-purple-400',
  ConvertedToRFQ: 'border-l-cyan-400', ConvertedToPO: 'border-l-emerald-400',
};

const STATUS_BADGE: Record<string, { bg: string; label: string }> = {
  Draft: { bg: 'bg-amber-100 text-amber-700', label: 'Draft' },
  Submitted: { bg: 'bg-blue-100 text-blue-700', label: 'Submitted' },
  Approved: { bg: 'bg-green-100 text-green-700', label: 'Approved' },
  Rejected: { bg: 'bg-red-100 text-red-700', label: 'Rejected' },
  AutoGenerated: { bg: 'bg-purple-100 text-purple-700', label: 'Auto-Generated' },
  ConvertedToRFQ: { bg: 'bg-cyan-100 text-cyan-700', label: 'To RFQ' },
  ConvertedToPO: { bg: 'bg-emerald-100 text-emerald-700', label: 'To PO' },
};

const PRIORITY_COLORS: Record<string, string> = {
  Low: 'bg-gray-100 text-gray-600', Normal: 'bg-blue-100 text-blue-700',
  High: 'bg-orange-100 text-orange-700', Urgent: 'bg-red-100 text-red-700',
};

function fmtDate(s?: string) {
  return s ? new Date(s).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : '—';
}

function SkeletonRow() {
  return (
    <tr>{[120, 100, 80, 70, 90, 80, 60, 90].map((w, i) => (
      <td key={i} className="px-4 py-3">
        <div className="h-3 bg-gray-100 rounded-full animate-pulse" style={{ width: w }} />
      </td>
    ))}</tr>
  );
}

function StatusBadge({ status }: { status: string }) {
  const cfg = STATUS_BADGE[status] ?? { bg: 'bg-gray-100 text-gray-600', label: status };
  return <span className={`inline-flex px-2.5 py-1 rounded-full text-xs font-medium ${cfg.bg}`}>{cfg.label}</span>;
}

function PriorityBadge({ priority }: { priority: string }) {
  return <span className={`inline-flex px-2 py-0.5 rounded text-xs font-medium ${PRIORITY_COLORS[priority] ?? 'bg-gray-100 text-gray-600'}`}>{priority}</span>;
}

function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) {
  return (
    <div className="fixed inset-0 bg-black/40 z-50 flex items-start justify-center pt-6 pb-4 overflow-y-auto">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl mx-4">
        <div className="flex items-center justify-between px-6 py-4 border-b">
          <h2 className="text-lg font-bold text-gray-900">{title}</h2>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-600"><X className="w-5 h-5" /></button>
        </div>
        {children}
      </div>
    </div>
  );
}

function CreateRequisitionModal({ onClose, onCreated }: { onClose: () => void; onCreated: () => void }) {
  const { data: stores = [] } = useStores();
  const [itemSearch, setItemSearch] = useState('');
  const [querySearch, setQuerySearch] = useState<string | undefined>(undefined);
  const { data: items = [] } = useInventoryItems(querySearch);
  const [storeId, setStoreId] = useState('');
  const [priority, setPriority] = useState('Normal');
  const [requiredByDate, setRequiredByDate] = useState('');
  const [justification, setJustification] = useState('');
  const [lines, setLines] = useState<{ itemId: string; itemName: string; requestedQty: number; unitOfMeasure: string }[]>([]);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    const t = setTimeout(() => setQuerySearch(itemSearch || undefined), 300);
    return () => clearTimeout(t);
  }, [itemSearch]);

  const addLine = (item: ItemDto) => {
    if (lines.some(l => l.itemId === item.id)) return;
    setLines(prev => [...prev, { itemId: item.id, itemName: item.itemName, requestedQty: 1, unitOfMeasure: item.unit ?? 'Nos' }]);
  };

  const submit = async () => {
    if (!storeId) { setError('Please select a store.'); return; }
    if (lines.length === 0) { setError('Add at least one item.'); return; }
    setBusy(true); setError('');
    try {
      await inventoryRequisitionApi.create({
        storeId, priority,
        requiredByDate: requiredByDate || undefined,
        justification: justification || undefined,
        items: lines.map(l => ({ itemMasterId: l.itemId, requestedQty: l.requestedQty, unitOfMeasure: l.unitOfMeasure })),
      });
      onCreated();
    } catch (e: any) {
      setError(e?.response?.data ?? e?.message ?? 'Failed to create requisition.');
    } finally { setBusy(false); }
  };

  return (
    <Modal title="New Purchase Requisition" onClose={onClose}>
      <div className="p-6 space-y-4 max-h-[68vh] overflow-y-auto">
        {error && <p className="text-sm text-red-600 bg-red-50 border border-red-200 rounded-lg px-3 py-2">{error}</p>}
        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Store <span className="text-red-500">*</span></label>
            <select value={storeId} onChange={e => setStoreId(e.target.value)}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-blue-500">
              <option value="">— Select Store —</option>
              {stores.map(s => <option key={s.id} value={s.id}>{s.storeName} ({s.storeType})</option>)}
            </select>
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Priority</label>
            <select value={priority} onChange={e => setPriority(e.target.value)}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-blue-500">
              {['Low', 'Normal', 'High', 'Urgent'].map(p => <option key={p}>{p}</option>)}
            </select>
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Required By</label>
            <input type="date" value={requiredByDate} onChange={e => setRequiredByDate(e.target.value)}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500" />
          </div>
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Search & Add Items</label>
          <input value={itemSearch} onChange={e => setItemSearch(e.target.value)} placeholder="Type to search items…"
            className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 mb-2" />
          <select className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm bg-white"
            onChange={e => { const item = items.find(i => i.id === e.target.value); if (item) addLine(item); (e.target as HTMLSelectElement).value = ''; }}>
            <option value="">— Click to add item —</option>
            {items.map(it => <option key={it.id} value={it.id}>{it.itemName} ({it.unit})</option>)}
          </select>
        </div>
        {lines.length > 0 && (
          <div className="rounded-lg border border-gray-200 overflow-hidden">
            <table className="w-full text-sm">
              <thead className="bg-gray-50 border-b">
                <tr>{['Item', 'Unit', 'Qty', ''].map(h => <th key={h} className="text-left px-3 py-2 text-xs font-semibold text-gray-500 uppercase">{h}</th>)}</tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                {lines.map((l, i) => (
                  <tr key={i}>
                    <td className="px-3 py-2 font-medium text-gray-900">{l.itemName}</td>
                    <td className="px-3 py-2 text-gray-500">{l.unitOfMeasure}</td>
                    <td className="px-3 py-2">
                      <input type="number" min={1} value={l.requestedQty}
                        onChange={e => setLines(prev => { const n = [...prev]; n[i] = { ...n[i], requestedQty: parseInt(e.target.value) || 1 }; return n; })}
                        className="border rounded px-2 py-1 w-20 text-center text-sm" />
                    </td>
                    <td className="px-3 py-2">
                      <button onClick={() => setLines(prev => prev.filter((_, idx) => idx !== i))}
                        className="text-red-400 hover:text-red-600"><X className="w-4 h-4" /></button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Justification</label>
          <textarea value={justification} onChange={e => setJustification(e.target.value)} rows={2}
            className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500" />
        </div>
      </div>
      <div className="flex justify-end gap-3 px-6 py-4 border-t bg-gray-50 rounded-b-2xl">
        <button onClick={onClose} className="px-4 py-2 text-sm border border-gray-300 rounded-lg hover:bg-gray-50 text-gray-700">Cancel</button>
        <button onClick={submit} disabled={busy || lines.length === 0}
          className="px-4 py-2 text-sm bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50 font-medium">
          {busy ? 'Creating…' : 'Create Requisition'}
        </button>
      </div>
    </Modal>
  );
}

function CreatePoFromRequisitionModal({ req, onClose, onCreated }: { req: any; onClose: () => void; onCreated: () => void }) {
  const [vendors, setVendors] = useState<VendorDto[]>([]);
  const [branches, setBranches] = useState<any[]>([]);
  const [vendorId, setVendorId] = useState('');
  const [branchId, setBranchId] = useState('');
  const [expectedDelivery, setExpectedDelivery] = useState('');
  const [notes, setNotes] = useState('');
  const [lines, setLines] = useState<{ itemId: string; itemName: string; requestedQty: number; orderedQty: number; unitPrice: number; gstPercent: number; unit: string }[]>([]);
  const [busy, setBusy] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    Promise.all([
      inventoryVendorApi.list().then(r => r.items ?? []),
      branchesApi.getAll().then(r => r.data?.branches ?? []),
      inventoryRequisitionApi.get(req.id),
    ]).then(([v, b, fullReq]) => {
      setVendors(v);
      setBranches(b);
      setBranchId(fullReq.branchId ?? '');
      setLines((fullReq.items ?? []).map((it: any) => ({
        itemId: it.itemId ?? it.itemMasterId,
        itemName: it.item?.itemName ?? it.itemName ?? '—',
        requestedQty: it.requestedQty ?? it.quantity ?? 0,
        orderedQty: it.requestedQty ?? it.quantity ?? 0,
        unitPrice: 0,
        gstPercent: 0,
        unit: it.unitOfMeasure ?? it.unit ?? 'Nos',
      })));
      setLoading(false);
    }).catch(e => { setError(e?.message ?? 'Failed to load requisition.'); setLoading(false); });
  }, [req.id]);

  const lineTotal  = lines.reduce((s, l) => s + l.orderedQty * l.unitPrice, 0);
  const gstTotal   = lines.reduce((s, l) => s + l.orderedQty * l.unitPrice * l.gstPercent / 100, 0);
  const grandTotal = lineTotal + gstTotal;

  const submit = async () => {
    if (!vendorId) { setError('Select a vendor.'); return; }
    if (!branchId) { setError('Select a branch.'); return; }
    if (lines.some(l => l.unitPrice <= 0)) { setError('Enter unit price for all items.'); return; }
    setBusy(true); setError('');
    try {
      const body: ConvertToPORequest = {
        branchId,
        vendorId,
        expectedDeliveryDate: expectedDelivery || undefined,
        notes: notes || undefined,
        items: lines.map(l => ({
          itemId: l.itemId,
          orderedQty: l.orderedQty,
          unitPrice: l.unitPrice,
          gstPercent: l.gstPercent,
          unit: l.unit,
        })),
      };
      await inventoryRequisitionApi.convertToPO(req.id, body);
      toast.success('Purchase Order created from Requisition!');
      onCreated();
    } catch (e: any) {
      setError(e?.response?.data ?? e?.message ?? 'Failed to create PO.');
    } finally { setBusy(false); }
  };

  return (
    <Modal title={`Create PO from ${req.requisitionNumber}`} onClose={onClose}>
      <div className="p-6 space-y-4 max-h-[68vh] overflow-y-auto">
        {loading && <p className="text-sm text-gray-500">Loading requisition details…</p>}
        {error && <p className="text-sm text-red-600 bg-red-50 border border-red-200 rounded-lg px-3 py-2">{error}</p>}
        {!loading && (<>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Vendor <span className="text-red-500">*</span></label>
              <select value={vendorId} onChange={e => setVendorId(e.target.value)}
                className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-blue-500">
                <option value="">— Select Vendor —</option>
                {vendors.map(v => <option key={v.id} value={v.id}>{v.name} ({v.vendorCode})</option>)}
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Branch <span className="text-red-500">*</span></label>
              <select value={branchId} onChange={e => setBranchId(e.target.value)}
                className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-blue-500">
                <option value="">— Select Branch —</option>
                {branches.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Expected Delivery</label>
              <input type="date" value={expectedDelivery} onChange={e => setExpectedDelivery(e.target.value)}
                className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500" />
            </div>
          </div>

          {lines.length > 0 && (
            <div className="rounded-lg border border-gray-200 overflow-hidden">
              <p className="px-4 py-2 text-xs text-gray-500 bg-gray-50 border-b">Enter pricing for each item — quantities pre-filled from the requisition.</p>
              <table className="w-full text-sm">
                <thead className="bg-gray-50 border-b">
                  <tr>{['Item', 'Unit', 'Req Qty', 'Order Qty', 'Unit Price ₹', 'GST%', 'Total'].map(h =>
                    <th key={h} className="text-left px-3 py-2 text-xs font-semibold text-gray-500 uppercase">{h}</th>)}</tr>
                </thead>
                <tbody className="divide-y divide-gray-100">
                  {lines.map((l, i) => (
                    <tr key={i}>
                      <td className="px-3 py-2 font-medium text-gray-900 text-xs">{l.itemName}</td>
                      <td className="px-3 py-2 text-gray-500 text-xs">{l.unit}</td>
                      <td className="px-3 py-2 text-gray-400 text-xs font-mono">{l.requestedQty}</td>
                      <td className="px-3 py-2">
                        <input type="number" min={1} value={l.orderedQty}
                          onChange={e => setLines(prev => { const n = [...prev]; n[i] = { ...n[i], orderedQty: parseInt(e.target.value) || 1 }; return n; })}
                          className="border rounded px-2 py-1 w-16 text-center text-sm" />
                      </td>
                      <td className="px-3 py-2">
                        <input type="number" min={0} step={0.01} value={l.unitPrice}
                          onChange={e => setLines(prev => { const n = [...prev]; n[i] = { ...n[i], unitPrice: parseFloat(e.target.value) || 0 }; return n; })}
                          className="border rounded px-2 py-1 w-24 text-right text-sm" />
                      </td>
                      <td className="px-3 py-2">
                        <input type="number" min={0} max={100} step={0.5} value={l.gstPercent}
                          onChange={e => setLines(prev => { const n = [...prev]; n[i] = { ...n[i], gstPercent: parseFloat(e.target.value) || 0 }; return n; })}
                          className="border rounded px-2 py-1 w-16 text-center text-sm" />
                      </td>
                      <td className="px-3 py-2 text-right font-mono text-xs">{(l.orderedQty * l.unitPrice * (1 + l.gstPercent / 100)).toFixed(2)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
              <div className="px-4 py-2 bg-gray-50 border-t flex justify-end gap-4">
                <span className="text-sm text-gray-500">Subtotal: ₹{lineTotal.toFixed(2)}</span>
                <span className="text-sm text-gray-500">GST: ₹{gstTotal.toFixed(2)}</span>
                <span className="text-sm font-semibold text-gray-700">Grand Total: ₹{grandTotal.toFixed(2)}</span>
              </div>
            </div>
          )}

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Notes</label>
            <textarea value={notes} onChange={e => setNotes(e.target.value)} rows={2}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500" />
          </div>
        </>)}
      </div>
      <div className="flex justify-end gap-3 px-6 py-4 border-t bg-gray-50 rounded-b-2xl">
        <button onClick={onClose} className="px-4 py-2 text-sm border border-gray-300 rounded-lg hover:bg-gray-50 text-gray-700">Cancel</button>
        <button onClick={submit} disabled={busy || loading}
          className="px-4 py-2 text-sm bg-emerald-600 text-white rounded-lg hover:bg-emerald-700 disabled:opacity-50 font-medium">
          {busy ? 'Creating PO…' : 'Create Purchase Order'}
        </button>
      </div>
    </Modal>
  );
}

export default function RequisitionsPage() {
  const [rows, setRows] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [search, setSearch] = useState('');
  const [statusTab, setStatusTab] = useState('All');
  const [showCreate, setShowCreate] = useState(false);
  const [acting, setActing] = useState<string | null>(null);
  const [expanded, setExpanded] = useState<string | null>(null);
  const [evalResult, setEvalResult] = useState<(EvaluatePolicyPathResult & { reqNumber: string }) | null>(null);
  const [createPoFromReq, setCreatePoFromReq] = useState<any | null>(null);

  const load = useCallback(async () => {
    setLoading(true); setError(null);
    try { const d = await inventoryRequisitionApi.list({ pageSize: 100 }); setRows(d.items ?? []); }
    catch (err: any) { setError(err?.response?.data ?? err?.message ?? 'Failed to load.'); }
    finally { setLoading(false); }
  }, []);

  useEffect(() => { load(); }, [load]);

  const filtered = useMemo(() =>
    rows.filter(r => statusTab === 'All' || r.status === statusTab)
        .filter(r => !search || r.requisitionNumber?.toLowerCase().includes(search.toLowerCase())),
    [rows, statusTab, search]);

  const doAction = async (id: string, action: () => Promise<unknown>, label: string) => {
    setActing(id + label);
    try { await action(); toast.success(`${label} successful.`); await load(); }
    catch (err: any) { toast.error(err?.response?.data ?? err?.message ?? `${label} failed.`); await load(); }
    finally { setActing(null); }
  };

  return (
    <div className="p-6 space-y-5">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Purchase Requisitions</h1>
          <p className="text-sm text-gray-500 mt-0.5">Manual and auto-generated stock replenishment requests</p>
        </div>
        <div className="flex items-center gap-2">
          <button onClick={load} className="p-2 rounded-lg border border-gray-200 hover:bg-gray-50" title="Refresh">
            <RefreshCw className="w-4 h-4 text-gray-500" />
          </button>
          <button onClick={() => setShowCreate(true)}
            className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700">
            <Plus className="w-4 h-4" /> New Requisition
          </button>
        </div>
      </div>

      <div className="flex items-center gap-2 flex-wrap">
        {STATUS_TABS.map(t => (
          <button key={t.key} onClick={() => setStatusTab(t.key)}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-full border text-xs font-medium transition-colors
              ${statusTab === t.key ? t.activeClass : 'bg-white border-gray-200 text-gray-600 hover:border-gray-300'}`}>
            <span className={`w-2 h-2 rounded-full ${t.dot}`} />
            {t.label}
          </button>
        ))}
      </div>

      <div className="relative max-w-xs">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
        <input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search by req. number…"
          className="w-full pl-9 pr-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500" />
      </div>

      {error && (
        <div className="bg-red-50 border border-red-200 rounded-lg px-4 py-3 flex items-center justify-between">
          <p className="text-red-700 text-sm">{error}</p>
          <button onClick={load} className="text-red-700 text-xs underline font-medium">Retry</button>
        </div>
      )}

      <div className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
        <table className="w-full text-sm">
          <thead className="bg-gray-50 border-b border-gray-200">
            <tr>
              {['Req #', 'Store', 'Status', 'Priority', 'Required By', 'Created', 'Items', 'Actions'].map(h => (
                <th key={h} className="text-left px-4 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wide">{h}</th>
              ))}
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {loading ? Array.from({ length: 5 }).map((_, i) => <SkeletonRow key={i} />) :
             filtered.length === 0 ? (
               <tr><td colSpan={8} className="px-4 py-16 text-center">
                 <Package className="w-10 h-10 text-gray-200 mx-auto mb-3" />
                 <p className="text-gray-400 text-sm">No requisitions found</p>
               </td></tr>
             ) : filtered.map(r => (
              <React.Fragment key={r.id}>
                <tr className={`border-l-4 ${STATUS_BORDER[r.status] ?? 'border-l-transparent'} hover:bg-gray-50 transition-colors`}>
                  <td className="px-4 py-3">
                    <Link href={`/admin/inventory/requisitions/${r.id}`}
                      className="font-mono font-semibold text-blue-600 hover:text-blue-800 text-xs">{r.requisitionNumber}</Link>
                  </td>
                  <td className="px-4 py-3 text-gray-600 text-xs">{r.storeName ?? '—'}</td>
                  <td className="px-4 py-3"><StatusBadge status={r.status} /></td>
                  <td className="px-4 py-3"><PriorityBadge priority={r.priority} /></td>
                  <td className="px-4 py-3 text-gray-500 text-xs">{fmtDate(r.requiredByDate)}</td>
                  <td className="px-4 py-3 text-gray-500 text-xs">{fmtDate(r.createdAt)}</td>
                  <td className="px-4 py-3">
                    <button onClick={() => setExpanded(expanded === r.id ? null : r.id)}
                      className="text-xs text-blue-600 hover:underline">
                      {r.items?.length ?? 0} items {expanded === r.id ? '▲' : '▼'}
                    </button>
                  </td>
                  <td className="px-4 py-3">
                    <div className="flex items-center gap-1 flex-wrap">
                      {r.status === 'Draft' && (
                        <button onClick={() => doAction(r.id, () => inventoryRequisitionApi.submit(r.id), 'Submit')}
                          disabled={acting === r.id + 'Submit'}
                          className="flex items-center gap-1 px-2 py-1 text-xs bg-blue-600 text-white rounded hover:bg-blue-700 disabled:opacity-50">
                          <Send className="w-3 h-3" /> Submit
                        </button>
                      )}
                      {r.status === 'Submitted' && (<>
                        <button onClick={() => doAction(r.id, () => inventoryRequisitionApi.approve(r.id), 'Approve')}
                          disabled={acting === r.id + 'Approve'}
                          className="flex items-center gap-1 px-2 py-1 text-xs bg-green-600 text-white rounded hover:bg-green-700 disabled:opacity-50">
                          <CheckCircle className="w-3 h-3" /> Approve
                        </button>
                        <button onClick={() => doAction(r.id, () => inventoryRequisitionApi.reject(r.id), 'Reject')}
                          disabled={acting === r.id + 'Reject'}
                          className="flex items-center gap-1 px-2 py-1 text-xs bg-red-600 text-white rounded hover:bg-red-700 disabled:opacity-50">
                          <XCircle className="w-3 h-3" /> Reject
                        </button>
                      </>)}
                      {r.status === 'Approved' && (<>
                        <button onClick={async () => {
                          setActing(r.id + 'Evaluate');
                          try {
                            const result = await inventoryRequisitionApi.evaluatePath(r.id);
                            setEvalResult({ ...result, reqNumber: r.requisitionNumber });
                            await load();
                          } catch (err: any) {
                            toast.error(err?.response?.data ?? err?.message ?? 'Evaluate failed.');
                          } finally { setActing(null); }
                        }}
                          disabled={acting === r.id + 'Evaluate'}
                          className="flex items-center gap-1 px-2 py-1 text-xs bg-purple-600 text-white rounded hover:bg-purple-700 disabled:opacity-50">
                          <GitBranch className="w-3 h-3" /> Evaluate
                        </button>
                        <button onClick={() => setCreatePoFromReq(r)}
                          className="flex items-center gap-1 px-2 py-1 text-xs bg-emerald-600 text-white rounded hover:bg-emerald-700">
                          <ShoppingCart className="w-3 h-3" /> Create PO
                        </button>
                      </>)}
                    </div>
                  </td>
                </tr>
                {expanded === r.id && r.items?.length > 0 && (
                  <tr>
                    <td colSpan={8} className="px-8 py-3 bg-blue-50/30 border-l-4 border-l-blue-200">
                      <div className="rounded-lg border border-gray-200 overflow-hidden bg-white">
                        <table className="w-full text-xs">
                          <thead className="bg-gray-50 border-b">
                            <tr>{['Item', 'Unit', 'Qty'].map(h => <th key={h} className="text-left px-3 py-2 font-semibold text-gray-500 uppercase">{h}</th>)}</tr>
                          </thead>
                          <tbody className="divide-y divide-gray-100">
                            {r.items.map((item: any, idx: number) => (
                              <tr key={idx}>
                                <td className="px-3 py-2">{item.itemName}</td>
                                <td className="px-3 py-2 text-gray-500">{item.unitOfMeasure}</td>
                                <td className="px-3 py-2 font-mono font-semibold">{item.requestedQty}</td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    </td>
                  </tr>
                )}
              </React.Fragment>
            ))}
          </tbody>
        </table>
      </div>

      {showCreate && (
        <CreateRequisitionModal
          onClose={() => setShowCreate(false)}
          onCreated={() => { setShowCreate(false); load(); toast.success('Requisition created!'); }}
        />
      )}
      {createPoFromReq && (
        <CreatePoFromRequisitionModal
          req={createPoFromReq}
          onClose={() => setCreatePoFromReq(null)}
          onCreated={() => { setCreatePoFromReq(null); load(); }}
        />
      )}
      {evalResult && (
        <div className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center">
          <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md mx-4 p-6 space-y-4">
            <div className="flex items-center justify-between">
              <h2 className="text-lg font-bold text-gray-900">Evaluation Result</h2>
              <button onClick={() => setEvalResult(null)} className="text-gray-400 hover:text-gray-600"><X className="w-5 h-5" /></button>
            </div>
            <div className="text-sm text-gray-600">Requisition: <span className="font-mono font-semibold">{evalResult.reqNumber}</span></div>
            <div className={`rounded-lg p-4 border-2 ${
              evalResult.recommendedPath === 'DirectPO' ? 'border-green-400 bg-green-50' : 'border-blue-400 bg-blue-50'
            }`}>
              <p className="text-lg font-bold ${
                evalResult.recommendedPath === 'DirectPO' ? 'text-green-700' : 'text-blue-700'
              }">
                Recommended: {evalResult.recommendedPath === 'DirectPO' ? '🛒 Direct PO' : '📋 RFQ Required'}
              </p>
              <p className="text-sm mt-1 text-gray-700">{evalResult.reason}</p>
            </div>
            {evalResult.estimatedValue > 0 && (
              <p className="text-sm text-gray-600">Estimated Value: <span className="font-semibold">₹{evalResult.estimatedValue.toLocaleString('en-IN')}</span></p>
            )}
            {evalResult.policyName && (
              <p className="text-xs text-gray-500">Policy: {evalResult.policyName}</p>
            )}
            <p className="text-xs text-gray-500">
              {evalResult.recommendedPath === 'RFQ'
                ? 'Go to RFQ → New RFQ and link this requisition to create an RFQ from it.'
                : 'Go to Purchase Orders → New PO to create a direct purchase order.'}
            </p>
            <div className="flex justify-end">
              <button onClick={() => setEvalResult(null)}
                className="px-4 py-2 text-sm bg-gray-800 text-white rounded-lg hover:bg-gray-900">Close</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
